server:
  port: 8080

mongodb:
  dbname: "demo"
  dbcollection: "books"
  dbuser: "user_name"
  dbpassword: "user_pass"
  dbhost: "localhost:27017"

redis:
  host: "localhost:6379"

auth:
  # this is just for study purpose
  secret: "4Ja67+nRUvEUg/fDpbnnVw="