name: Check PR

on: pull_request

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.x in order to write go.list file
        uses: actions/setup-go@v2

      - name: WriteGoList
        run: go list -json -m all > go.list

      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
